# Configuration spécifique au product-service
server.port=8081
spring.application.name=product-service
eureka.instance.prefer-ip-address=false

# Message personnalisé (pour tester)
app.message=Configuration chargée depuis Config Server pour Product Service