# Configuration spécifique au product-service
server.port=8081
spring.application.name=product-service
eureka.instance.prefer-ip-address=false

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/products_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Message test
app.message=Configuration chargee depuis Config Server pour Product Service