spring:
  application:
    name: product-service
server:
  port: 8081
# Configuration Eureka Client
eureka:
  client:
    service-url.defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: false