spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: file:///${user.dir}/../  # racine du projet global avec .git
          search-paths: config-repo     # sous-dossier contenant les configs
          #ou
        #native:
          # chemin vers le dossier config-repo
          #search-locations: file:///${user.dir}/../config-repo/

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: false